openapi: 3.0.0

# INFO SECTION
info:
  title: ESP APIs
  version: 21.2.0
  description: "ESP APIs technical reference."
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

# TAGS
tags:
  - name: Get Key
    description: Get key endpoint
    externalDocs:
      description: Get key Documentation
      url: https://namirialgroup.github.io/esp-docs/integrations/getkey
  - name: Login
    description: Login with SPID/CIE
    externalDocs:
      description: Login Documentation
      url: https://namirialgroup.github.io/esp-docs/integrations/login
  - name: Get user
    description: Get user endpoint
    externalDocs:
      description: Get user Documentation
      url: https://namirialgroup.github.io/esp-docs/integrations/token

# PATHS
paths:
  # GET KEY
  /sslprotected/<environment_name>/getKey.php:
    get:
      tags:
        -  Get Key
      summary: Get a authn key to start an authentication flow
      security:
        - sslCertificate: [ ]
      parameters:
        - in: query
          name: level
          schema:
            type: string
          required: true
          description: The authentication level. It should be refered to L1-L2-L3 (The L letter should be removed)
          example: 1
        - in: query
          name: attributes
          schema:
            type: string
          required: true
          description: The attribute parameter (Basic-Full)
          example: Full
      responses:
        '200':
          description: The authn key
          content:
            text/html:
              schema:
                $ref: '#/components/schemas/GetKeyResponse'
        '400 Error code 1':
          description: final url empty
        '400 Error code 2':
          description: level param invalid
        '400 Error code 3':
          description: attributes invalid
        '403 Error code 4':
          description: authn key invalid
        '403 Error code 5':
          description: authn key refers to an invalid service provider
        '403 Error code 6':
          description: authn key missing
        '403 Error code 11':
          description: level mismatch between level parameter and authnkey  

  # Login
  /<environment_name>/spid_login.php:
    get:
      tags:
        - Login
      summary: Login with SPID with a browser 
      parameters:
        - in: query
          name: level
          schema:
            type: string
          required: true
          description: The authentication level. It should be refered to L1-L2-L3 (The L letter should be removed)
          example: 1
        - in: query
          name: attributes
          schema:
            type: string
          required: true
          description: The attribute parameter (Basic-Full)
          example: Full
        - in: query
          name: final
          schema:
            type: string
          required: true
          description: It's the redirect url called at the end of the authentication process (It should be comunicated during the assessment phase) 
          example: http://localhost
        - in: query
          name: authnKey
          schema:
            type: string
          required: true
          description: It's the authn key that has been given at the get key endpoint
          example: c1BUQkJ4d3hYUWV6ZEQ4TktlSWV6ZmozVy9HNzNrQlcyRFlvMTB1TTlGKzE3dWNjdHNLV2RUN0pVNTNJQnhsVnNMMWhBS0lucGNxMC9qY0c3U3BWYlc5dktOMXFvVkhyYUIrdDFBd1VBWGM5bERzS1RnVzd1V251R3pWUEpiUmc
      responses:
        '200':
          description: It starts an authentication process with a url redirect
        '400 Error code 7-8':
          description: generic authentication errors
        '400 Error code 9':
          description: missing redirect type
        '403 Error code 10':
          description: spid level < authnkey level
        '403 Error code 12':
          description: spid level refer to an active session < authnkey level
          
  /<environment_name>/cie_login.php:
    get:
      tags:
        - Login
      summary: Login with CIE with a browser
      parameters:
        - in: query
          name: level
          schema:
            type: string
          required: true
          description: The authentication level. It should be refered to L1-L2-L3 (The L letter should be removed)
          example: 1
        - in: query
          name: attributes
          schema:
            type: string
          required: true
          description: The attribute parameter (Basic-Full)
          example: Full
        - in: query
          name: final
          schema:
            type: string
          required: true
          description: It's the redirect url called at the end of the authentication process (It should be comunicated during the assessment phase)
          example: http://localhost
        - in: query
          name: authnKey
          schema:
            type: string
          required: true
          description: It's the authn key that has been given at the get key endpoint
          example: c1BUQkJ4d3hYUWV6ZEQ4TktlSWV6ZmozVy9HNzNrQlcyRFlvMTB1TTlGKzE3dWNjdHNLV2RUN0pVNTNJQnhsVnNMMWhBS0lucGNxMC9qY0c3U3BWYlc5dktOMXFvVkhyYUIrdDFBd1VBWGM5bERzS1RnVzd1V251R3pWUEpiUmc
      responses:
        '200':
          description: It starts an authentication process with a url redirect
        '400 Error code 7-8':
          description: generic authentication errors
        '400 Error code 9':
          description: missing redirect type
        '403 Error code 10':
          description: spid level < authnkey level
        '403 Error code 12':
          description: spid level refer to an active session < authnkey level
 
  #Get User
  /sslprotected/<environment_name>/getUser.php:
    get:
      tags:
        -  Get user
      summary: Get a user JWT
      security:
        - sslCertificate: [ ]
      parameters:
        - in: query
          name: ID
          schema:
            type: string
          required: true
          description: The ESP user identifier
          example: _ecf182c0024338b109397ea3d04ab141
        - in: query
          name: key
          schema:
            type: string
          required: true
          description: The ESP session key
          example: _029da15302d1f7bf8a4ff9826b4489c3
      responses:
        '200':
          description: The authn key
          content:
            text/html:
              schema:
                $ref: '#/components/schemas/JWTBearerResponse'
        '400':
          description: missing key or ID parameter
        '403':
          description: SSL authentication error
        '403 Error code 3':
          description: missing session for key and id provided

externalDocs:
  description: Official ESP documentation
  url: https://namirialgroup.github.io/esp-docs/
servers:
  - url: https://esp-saas.test.namirialtsp.com
    description: (Test)
  - url: https://esp-saas.namirialtsp.com
    description: (Prod)
components:
  securitySchemes:
    sslCertificate: # arbitrary name for the security scheme
      type: http
      scheme: basic    
  responses:
    ForbiddenError:
      description: System has not permission to access to the entity
  schemas:
    GetKeyResponse:
      type: string
      example: c1BUQkJ4d3hYUWV6ZEQ4TktlSWV6ZmozVy9HNzNrQlcyRFlvMTB1TTlGKzE3dWNjdHNLV2RUN0pVNTNJQnhsVnNMMWhBS0lucGNxMC9qY0c3U3BWYlc5dktOMXFvVkhyYUIrdDFBd1VBWGM5bERzS1RnVzd1V251R3pWUEpiUmc
    JWTBearerResponse:
      type: string
      example: jwt that contains the SAML Assertion attributes
    